### ISSUE TITLE
can't initialize opengl

### ISSUE THREAD

**Issue by 11111000000** [david-vanderson/warp#2]
[az@thinky:~/Work/warp]$ racket ./client.rkt 
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
gl-context: glXCreateNewContext raised an error but (contrary to sta
ndards) returned a non-NULL context; ignoring possibly corrupt conte
xt                                                                 
draw: Could not initialize OpenGL!
  context...:
   /home/az/.racket/6.12/pkgs/mode-lambda/mode-lambda/backend/gl/uti
l.rkt:325:6                                                        
   /home/az/Work/warp/client.rkt:175:2: draw-screen
   /nix/store/w8irdkvdaq0g9z85fhp6dy4nlimbcw09-racket-6.12/share/rac
ket/collects/racket/private/more-scheme.rkt:148:2: call-with-break-p
arameterization                                                    
   /nix/store/w8irdkvdaq0g9z85fhp6dy4nlimbcw09-racket-6.12/share/rac
ket/collects/ffi/unsafe/atomic.rkt:72:13                           
   /nix/store/w8irdkvdaq0g9z85fhp6dy4nlimbcw09-racket-6.12/share/rac
ket/pkgs/gui-lib/mred/private/wx/common/canvas-mixin.rkt:144:4: do-o
n-paint method in ...mon/canvas-mixin.rkt:118:2                    
   /nix/store/w8irdkvdaq0g9z85fhp6dy4nlimbcw09-racket-6.12/share/rac
ket/pkgs/gui-lib/mred/private/wx/common/queue.rkt:428:6            
   /nix/store/w8irdkvdaq0g9z85fhp6dy4nlimbcw09-racket-6.12/share/rac
ket/pkgs/gui-lib/mred/private/wx/common/queue.rkt:479:32           
   (submod /home/az/Work/warp/client.rkt main): [running body]
canvas on-size 800 600

**Comment by david-vanderson** [comment]
Sounds like a driver problem but haven't heard back.
